/*Generated by xorm 2023-09-28 16:06:21,
FROM mysql to mysql*/ SET sql_mode='NO_BACKSLASH_ESCAPES'; 
CREATE TABLE IF NOT EXISTS `app_users` (`id` BIGINT(20) PRIMARY KEY AUTO_INCREMENT NOT NULL COMMENT 'id', `username` VARCHAR(32) NULL COMMENT '用户名', `age` INT(11) NULL COMMENT '年龄', `email` VARCHAR(255) NULL COMMENT '邮箱', `create_time` DATETIME NULL COMMENT '创建时间', `update_time` DATETIME NULL COMMENT '更新时间', `is_deleted` TINYINT(1) DEFAULT 0 NULL COMMENT '是否删除',
         `only_write` VARCHAR(255) NULL,
         `only_read` VARCHAR(255) NULL,
         `data` TEXT(65535) NULL,
         `city_name` VARCHAR(255) NULL,
         `province_name` VARCHAR(255) NULL,
         `r_k_string` VARCHAR(255) NULL,
         `r_k_map` TEXT(65535) NULL,
         `r_k_slicp` TEXT(65535) NULL) ENGINE=InnoDB DEFAULT CHARSET utf8; CREATE UNIQUE INDEX `UQE_app_users_id`
    ON `app_users` (`id`); 