POST http://localhost:9999/form
Content-Type: application/x-www-form-urlencoded

id=999&value=content

###

POST http://localhost:9999/user/save
Content-Type: application/json

{
  "name": "ohy",
  "email": "ohy@qq.com"
}

###
GET http://localhost:9999/admin/mw
Content-Type: application/json
Authorization: Basic {{username}} {{password}}


###
GET http://localhost:9999/ctx


###
GET http://localhost:9999/createCookie


###
POST http://localhost:9999/valid
Content-Type: application/json

{
  "name": "ohy",
  "email": "ohy@errordomain"
}

###
GET http://localhost:9999/respType


###
GET http://localhost:9999/group/test


### 测试signup
POST http://localhost:9999/signup
Content-Type: application/json

{
  "password": "ohy",
  "email": "ohy@errordomain"
}

### 测试登录 login
POST http://localhost:9999/login
Content-Type: application/json

{
  "password": "ohy",
  "email": "ohy@errordomain"
}

### 测试关注某人
POST http://localhost:9999/follow/6673953ef080f449d0c26c35
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkxMTA1MDksImlkIjoiNjY3Mzk1M2VmMDgwZjQ0OWQwYzI2YzM1In0.iDCDaEQYlIsXVgjbdIwht1g8R_20IcdXUAsHqDp6eOI

### 测试发送消息
POST http://localhost:9999/post
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkxMTA1MDksImlkIjoiNjY3Mzk1M2VmMDgwZjQ0OWQwYzI2YzM1In0.iDCDaEQYlIsXVgjbdIwht1g8R_20IcdXUAsHqDp6eOI

{
  "message": "你好啊~",
  "to": "ohy@errordomain"
}

### 测试历史消息分页
GET http://localhost:9999/posts/1/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MTkxMTA1MDksImlkIjoiNjY3Mzk1M2VmMDgwZjQ0OWQwYzI2YzM1In0.iDCDaEQYlIsXVgjbdIwht1g8R_20IcdXUAsHqDp6eOI


### 测试
GET http://localhost:9999/stats


### 测试iris基本使用
GET http://localhost:9999/cfg


### 测试iris获取路径参数
GET http://localhost:9999/testPath02/100


### 测试自定义宏
GET http://localhost:9999/jwdLint/36.000/-50.350

### 测试自定义宏2
GET http://localhost:9999/max/ab

### 测试自定义宏3
GET http://localhost:9999/username/kiwiii

### 测试404
GET http://localhost:9999/xxxxx